version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://user:password@db:5432/todo
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3006:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3000
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
       POSTGRES_USER: user
       POSTGRES_PASSWORD: password
       POSTGRES_DB: todo
    volumes:
       - pgdata:/var/lib/postgresql/data
       - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
